# This is a basic workflow to help you get started with Actions
name: CI - rodrigo.world website (pages-root-deploy)

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the pages-root-deploy branch
  push:
    branches: [pages-root-deploy]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup Node.js environment for npm scripts
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      # Install dependencies
      - name: Install dependencies
        run: npm ci
        
      # Run build process (copy src to root)
      - name: Build website
        run: npm run build
        
      # Deploy the built content from root directory
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '*'
          delete-removed: true
          no-cache: true
          private: true
