# Workflow para automatizar build e deploy para GitHub Pages usando peaceiris/actions-gh-pages
name: Build and Deploy to GitHub Pages

# Controla quando a ação será executada
on:
  # Aciona o workflow em push ou merge na branch main
  push:
    branches: [main]
  # Permite executar este workflow manualmente da aba Actions
  workflow_dispatch:

# Configurar permissões para o GITHUB_TOKEN - Fix para erro 403 no GitHub Actions Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  deployments: write

# Permitir apenas um deployment simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para build e deploy
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Faz checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4
      
      # Configura ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Instala dependências
      - name: Install dependencies
        run: npm ci
      
      # Executa o build para pasta dist
      - name: Build website
        run: |
          npm run build
          # Cria pasta dist se não existir
          mkdir -p dist
          # Copia todo conteúdo compilado para dist
          cp -r * dist/ 2>/dev/null || true
          # Remove arquivos desnecessários da dist
          cd dist
          rm -rf node_modules .git .github src package*.json .prettierrc .gitignore tags 2>/dev/null || true
      
      # Deploy para GitHub Pages usando peaceiris/actions-gh-pages
      # ATUALIZAÇÃO: Configurado para usar Personal Access Token (GH_PAT) para autenticação
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token personalizado do GitHub para autenticação (GH_PAT configurado nos secrets)
          github_token: ${{ secrets.GH_PAT }}
          # Diretório com conteúdo para publicar
          publish_dir: ./dist
          # Branch de destino para GitHub Pages
          publish_branch: gh-pages
          # Força push (substitui conteúdo anterior)
          force_orphan: true
          # Configurações de commit
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy from main branch: ${{ github.sha }}'
